version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
