version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
    password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
