name: Cron auto-release
on:
  schedule:
    - cron: "0 4 * * *"
permissions:
  contents: write
  packages: write
jobs:
  call-increment-tag-version:
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/increment-tag-version.yaml@v0.3.1
  call-publish:
    if: ${{ (needs.call-increment-tag-version.outputs.latest_tag_sha != '') && (github.sha != needs.call-increment-tag-version.outputs.latest_tag_sha) }}
    needs: [ call-increment-tag-version ]
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/publish.yaml@v0.3.1
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
    with:
      app_version: ${{ needs.call-increment-tag-version.outputs.new_tag_name }}
      enable_qemu: true
  create-release:
    needs: [ call-increment-tag-version, call-publish ]
    runs-on: ubuntu-20.04
    steps:
    - name: Create github release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.call-increment-tag-version.outputs.new_tag_name }}
        target_commitish: ${{ github.sha }}
        generate_release_notes: true
