name: Cron auto-release
on:
  schedule:
    - cron: "0 4 * * *"
permissions:
  contents: write
  packages: write
jobs:
  call-increment-tag-version:
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/increment-tag-version.yaml@v0.4.2
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
  call-publish:
    needs: [ call-increment-tag-version ]
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/publish.yaml@v0.4.2
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
    with:
      app_version: ${{ needs.call-increment-tag-version.outputs.new_tag_name }}
      enable_qemu: true
  create-release:
    needs: [ call-increment-tag-version, call-publish ]
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/create-release.yaml@v0.4.2
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
    with:
      tag_name: ${{ needs.call-increment-tag-version.outputs.new_tag_name }}
      target_commit_hash: ${{ github.sha }}
