name: Push
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '**'
jobs:
  call-test:
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/test.yaml@v0.4.1
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN_GITHUB_ACTIONS }}
    with:
      enable_qemu: true
