name: Release
on:
  release:
    types:
      - "published"
permissions:
  contents: read
  packages: write
jobs:
  call-test:
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/test.yaml@v0.3.1
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
  call-publish:
    needs: [ call-test ]
    uses: bluegosolutions/gl-gh-actions-workflows/.github/workflows/publish.yaml@v0.3.1
    secrets:
      username: ${{ secrets.IMAGE_GITHUB_USERNAME }}
      password: ${{ secrets.IMAGE_GITHUB_PASSWORD }}
    with:
      app_version: ${{ github.ref_name }}
